version: 2
jobs:
  build:
    working_directory: /app
    environment:
      DOCKER_IMAGE=dgoeke/clojure-terraform-aws
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ checksum "Dockerfile" }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t $DOCKER_IMAGE .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar $DOCKER_IMAGE
      - save_cache:
          key: v1-{{ checksum "Dockerfile" }}
          paths:
            - /caches/app.tar
      - deploy:
          name: Tag image and push to dockerhub
          command: |
            SHORT_SHA=$(git rev-parse --short HEAD)
            VERSION="0.1.${CIRCLE_BUILD_NUM}-${SHORT_SHA}"

            docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$VERSION
            docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD
            docker push $DOCKER_IMAGE
